// <auto-generated />
using System;
using BrightClean.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrightClean.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BrightClean.Domain.Entities.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressID"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressID");

                    b.HasIndex("ClientID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.AgentService", b =>
                {
                    b.Property<int>("AgentServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgentServiceID"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LaundryAgentID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PendingActivation")
                        .HasColumnType("bit");

                    b.Property<int>("RequestedAction")
                        .HasColumnType("int");

                    b.Property<int>("ServiceID")
                        .HasColumnType("int");

                    b.HasKey("AgentServiceID");

                    b.HasIndex("ServiceID");

                    b.HasIndex("LaundryAgentID", "ServiceID")
                        .IsUnique();

                    b.ToTable("AgentServices");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetEntity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("AdminID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FinalTotal")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("LaundryAgentID")
                        .HasColumnType("int");

                    b.Property<int?>("OfferID")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("AddressID");

                    b.HasIndex("ClientID");

                    b.HasIndex("LaundryAgentID");

                    b.HasIndex("OfferID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.BookingItem", b =>
                {
                    b.Property<int>("BookingItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingItemID"));

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiceID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPriceAtTimeOfBooking")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("BookingItemID");

                    b.HasIndex("BookingID");

                    b.HasIndex("ServiceID");

                    b.ToTable("BookingItems");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.BookingRating", b =>
                {
                    b.Property<int>("RatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingID"));

                    b.Property<string>("AgentComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AgentRating")
                        .HasColumnType("int");

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeliveryRating")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RatingID");

                    b.HasIndex("BookingID")
                        .IsUnique();

                    b.ToTable("BookingRatings");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.DeliveryTask", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("int");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int?>("DeliveryStaffID")
                        .HasColumnType("int");

                    b.Property<int>("DropoffAddressID")
                        .HasColumnType("int");

                    b.Property<int>("PickupAddressID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastProgressUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StageNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("TaskID");

                    b.HasIndex("DeliveryStaffID");

                    b.HasIndex("DropoffAddressID");

                    b.HasIndex("PickupAddressID");

                    b.HasIndex("BookingID", "StageNumber")
                        .IsUnique();

                    b.ToTable("DeliveryTasks");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.Offer", b =>
                {
                    b.Property<int>("OfferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferID"));

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LaundryAgentID")
                        .HasColumnType("int");

                    b.Property<int?>("MaxUsageCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinOrderValue")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("OfferCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("OfferID");

                    b.HasIndex("AdminID");

                    b.HasIndex("LaundryAgentID");

                    b.HasIndex("OfferCode")
                        .IsUnique();

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentProofURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByAdminID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentID");

                    b.HasIndex("BookingID")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Method");

                    b.HasIndex("ReviewedByAdminID");

                    b.HasIndex("Status");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.ServiceCatalogItem", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceID"));

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryModel")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("PricingModel")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ServiceID");

                    b.HasIndex("AdminID");

                    b.ToTable("ServiceCatalogItems");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.SystemStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LoginEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusID");

                    b.HasIndex("AdminID");

                    b.ToTable("SystemStatuses");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<bool>("TermsAccepted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNo")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.UserDocument", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentID"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByAdminID")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("DocumentID");

                    b.HasIndex("ReviewStatus");

                    b.HasIndex("ReviewedByAdminID");

                    b.HasIndex("UserID", "Type");

                    b.ToTable("UserDocuments");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.Admin", b =>
                {
                    b.HasBaseType("BrightClean.Domain.Entities.User");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.Client", b =>
                {
                    b.HasBaseType("BrightClean.Domain.Entities.User");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<decimal>("WalletBalance")
                        .HasColumnType("decimal(18,3)");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.DeliveryStaff", b =>
                {
                    b.HasBaseType("BrightClean.Domain.Entities.User");

                    b.Property<string>("BankAcc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrandfatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalIDNumber")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehicleMake")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasIndex("NationalIDNumber")
                        .IsUnique()
                        .HasFilter("[NationalIDNumber] IS NOT NULL");

                    b.HasIndex("PlateNumber")
                        .IsUnique()
                        .HasFilter("[PlateNumber] IS NOT NULL");

                    b.ToTable("DeliveryStaffs", (string)null);
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.LaundryAgent", b =>
                {
                    b.HasBaseType("BrightClean.Domain.Entities.User");

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<string>("BankAcc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommercialRegister")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrandfatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsStoreClosed")
                        .HasColumnType("bit");

                    b.Property<string>("NationalIDNumber")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("AddressID");

                    b.HasIndex("CommercialRegister")
                        .IsUnique()
                        .HasFilter("[CommercialRegister] IS NOT NULL");

                    b.HasIndex("NationalIDNumber")
                        .IsUnique()
                        .HasFilter("[NationalIDNumber] IS NOT NULL");

                    b.ToTable("LaundryAgents", (string)null);
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.Address", b =>
                {
                    b.HasOne("BrightClean.Domain.Entities.Client", "Client")
                        .WithMany("Addresses")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.AgentService", b =>
                {
                    b.HasOne("BrightClean.Domain.Entities.LaundryAgent", "LaundryAgent")
                        .WithMany("SubscribedServices")
                        .HasForeignKey("LaundryAgentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightClean.Domain.Entities.ServiceCatalogItem", "ServiceCatalogItem")
                        .WithMany("AgentServices")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LaundryAgent");

                    b.Navigation("ServiceCatalogItem");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("BrightClean.Domain.Entities.Admin", "Admin")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.Booking", b =>
                {
                    b.HasOne("BrightClean.Domain.Entities.Address", "Address")
                        .WithMany("Bookings")
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BrightClean.Domain.Entities.Client", "Client")
                        .WithMany("Bookings")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BrightClean.Domain.Entities.LaundryAgent", "LaundryAgent")
                        .WithMany("Bookings")
                        .HasForeignKey("LaundryAgentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BrightClean.Domain.Entities.Offer", "Offer")
                        .WithMany("Bookings")
                        .HasForeignKey("OfferID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("Client");

                    b.Navigation("LaundryAgent");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.BookingItem", b =>
                {
                    b.HasOne("BrightClean.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingItems")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightClean.Domain.Entities.ServiceCatalogItem", "ServiceCatalogItem")
                        .WithMany("BookingItems")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ServiceCatalogItem");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.BookingRating", b =>
                {
                    b.HasOne("BrightClean.Domain.Entities.Booking", "Booking")
                        .WithOne("Rating")
                        .HasForeignKey("BrightClean.Domain.Entities.BookingRating", "BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.DeliveryTask", b =>
                {
                    b.HasOne("BrightClean.Domain.Entities.Booking", "Booking")
                        .WithMany("DeliveryTasks")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightClean.Domain.Entities.DeliveryStaff", "DeliveryStaff")
                        .WithMany("DeliveryTasks")
                        .HasForeignKey("DeliveryStaffID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BrightClean.Domain.Entities.Address", "DropoffAddress")
                        .WithMany("DropoffTasks")
                        .HasForeignKey("DropoffAddressID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BrightClean.Domain.Entities.Address", "PickupAddress")
                        .WithMany("PickupTasks")
                        .HasForeignKey("PickupAddressID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("DeliveryStaff");

                    b.Navigation("DropoffAddress");

                    b.Navigation("PickupAddress");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.Notification", b =>
                {
                    b.HasOne("BrightClean.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.Offer", b =>
                {
                    b.HasOne("BrightClean.Domain.Entities.Admin", "CreatorAdmin")
                        .WithMany("CreatedOffers")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BrightClean.Domain.Entities.LaundryAgent", "ScopedAgent")
                        .WithMany("ScopedOffers")
                        .HasForeignKey("LaundryAgentID");

                    b.Navigation("CreatorAdmin");

                    b.Navigation("ScopedAgent");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.Payment", b =>
                {
                    b.HasOne("BrightClean.Domain.Entities.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("BrightClean.Domain.Entities.Payment", "BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrightClean.Domain.Entities.Admin", "ReviewedByAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("ReviewedByAdmin");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.ServiceCatalogItem", b =>
                {
                    b.HasOne("BrightClean.Domain.Entities.Admin", "Admin")
                        .WithMany("ManagedServices")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.SystemStatus", b =>
                {
                    b.HasOne("BrightClean.Domain.Entities.Admin", "Admin")
                        .WithMany("SystemStatuses")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.UserDocument", b =>
                {
                    b.HasOne("BrightClean.Domain.Entities.Admin", "ReviewedByAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BrightClean.Domain.Entities.User", "User")
                        .WithMany("Documents")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewedByAdmin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.Admin", b =>
                {
                    b.HasOne("BrightClean.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("BrightClean.Domain.Entities.Admin", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.Client", b =>
                {
                    b.HasOne("BrightClean.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("BrightClean.Domain.Entities.Client", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.DeliveryStaff", b =>
                {
                    b.HasOne("BrightClean.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("BrightClean.Domain.Entities.DeliveryStaff", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.LaundryAgent", b =>
                {
                    b.HasOne("BrightClean.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BrightClean.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("BrightClean.Domain.Entities.LaundryAgent", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.Address", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("DropoffTasks");

                    b.Navigation("PickupTasks");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.Booking", b =>
                {
                    b.Navigation("BookingItems");

                    b.Navigation("DeliveryTasks");

                    b.Navigation("Payment");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.Offer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.ServiceCatalogItem", b =>
                {
                    b.Navigation("AgentServices");

                    b.Navigation("BookingItems");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.User", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.Admin", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedOffers");

                    b.Navigation("ManagedServices");

                    b.Navigation("SystemStatuses");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.Client", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.DeliveryStaff", b =>
                {
                    b.Navigation("DeliveryTasks");
                });

            modelBuilder.Entity("BrightClean.Domain.Entities.LaundryAgent", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ScopedOffers");

                    b.Navigation("SubscribedServices");
                });
#pragma warning restore 612, 618
        }
    }
}
